name: Blackbright
title: A Coming soon Jekyll Template
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
email: samuelson@blackbright.co.za
description: A coming soon Jekyll template | blackbright
baseurl: ""
url: ""
author: Afronaut
googlebots:
robots:
google_analytics: 'UA-115564731-1'
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sass_dir: assets/css
  style: compressed
