# Site
name: Blackbright
title: "An Unorthodox blog to get you inspired and achieving more | Blackbright"
description: 'An Unorthodox blog to get you inspired and achieving more.'
meta_description: "An Unorthodox blog to get you inspired and achieving more."

logo: 'assets/images/logo.svg'
favicon: 'assets/images/favicon.png'

paginate: 15
baseurl: ""
url: 'http://www.blackbright.co.za'
google_analytics: 'UA-115564731-1'

disqus: ''
mailchimp-list: ''

googlebots:
robots:
author: Blackbright Media

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-sitemap
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge